service: get-event-kolkol

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    role: ${env:Lambda_Role}
    timeout: 120
    layers:
      - Ref: PythonRequirementsLambdaLayer

    events:
    - schedule: cron(0 0 * * ? *)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true

package:
  patterns:
    - "!.vscode/**"
    - "!.git/**"
    - "!.gitignore"
    - "!.serverless"
    - "!.serverless/**"
    - "!README.md"
    - "!package*.json"
    - "!requirements.txt"
    - "!node_modules/**"
    - "!__pycache__"
    - "!yarn.lock"
